version: 0.0
os: linux
files:
  - source: /
    destination: /opt/tomcat/webapps
    file_exists_behavior: OVERWRITE
permissions:
  - object: /opt/tomcat/webapps
    mode: 755
    owner: root
    group: root
    type:
      - directory
      - file
hooks:
  ApplicationStart:
    - location: startup.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: shutdown.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: shutdown.sh
      timeout: 300
      runas: root
