version: 0.2

env:
  variables:
    BRANCHNAME: "/usr/lib/jvm/java-8-openjdk-amd64"
    REPO: 'https://cernerrepos.net/maven'
    
phases:
  install:
    commands:
      - wget -O awscliv2.zip https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
      - unzip awscliv2.zip
      - ./aws/install
      - aws configure set default.region us-west-2
      - BUILD=`curl -L -0 https://jenkins-partners.cerner.com/job/cerner-corp/job/authorization-server-reactor/job/CLOUDAUTHZ-2697-develop/lastSuccessfulBuild/buildNumber`

  pre_build:
    commands:
      - wget -O output.txt https://jenkins-partners.cerner.com/job/cerner-corp/job/authorization-server-reactor/job/"$BRANCHNAME"/"$BUILD"/console
      - REPO='https://cernerrepos.net/maven'
      - ROOT=$(cat output.txt | grep target/ROOT.war | awk '{printf $8}' | sed 's/-SNAPSHOT//g')
      - CLIENT=$(cat output.txt | grep target/client.war | awk '{printf $8}'| sed 's/-SNAPSHOT//g')
      - MOCKS=$(cat output.txt | grep target/mocks.war | awk '{printf $8}'| sed 's/-SNAPSHOT//g')
      - rm -rf output.txt

  build:
    commands:
      - aws s3 cp s3://trust-app/prepare.sh .
      - chmod +x prepare.sh

  post_build:
    commands:
      - echo Entering post_build phase...
      - ./prepare.sh

artifacts:
  type: zip
  files:
    - 'ROOT.war'
    - 'client.war'
    - 'mocks.war'
    - 'appspec.yml'
    - 'startup.sh'
    - 'shutdown.sh'
